name: test
on:
  push:
    branches: ['main']
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go: ['1.19', '1.20']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install golang ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        check-latest: false
        cache: true
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -v -race -covermode=atomic ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v3
