name: test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21", "1.22", "1.23"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install golang ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: false
          cache: true
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -v -race -covermode=atomic ./...
    # - name: Lint
    #   uses: golangci/golangci-lint-action@v3
